#!/usr/bin/env python3
"""Generate the local Tory endorsement sensitivity report without updating forecasts.

Run: uv run python scripts/analyze_tory_endorsement.py
"""

from __future__ import annotations

import argparse
import csv
import json
import math
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from backend.analysis.endorsement_scenarios import NAMES, build_analysis


def write_report(output: Path) -> None:
    report = build_analysis(ROOT)
    scenarios = report["scenarios"]
    # A correctness gate over every emitted feasible scenario, not a model evaluation.
    for scenario in [
        *scenarios,
        *report["alexander_entry"]["extensions"],
        *report["consolidation"]["scenarios"],
    ]:
        if scenario["feasible"]:
            shares = scenario["shares"]
            if min(shares.values()) < -1e-9 or not math.isclose(sum(shares.values()), 100):
                raise ValueError("Scenario failed conservation check.")
        elif scenario["shares"] is not None:
            raise ValueError("An impossible scenario must not expose adjusted shares.")

    output.mkdir(parents=True, exist_ok=True)
    serialized = json.dumps(report, indent=2, ensure_ascii=False, allow_nan=False) + "\n"
    (output / "scenarios.json").write_text(serialized)
    template = (ROOT / "backend/analysis/endorsement_report.html").read_text()
    (output / "index.html").write_text(
        template.replace("@@DATA@@", serialized.replace("<", "\\u003c"))
    )

    timings = {row["id"]: row for row in report["timings"]}
    fields = [
        "baseline_id",
        "recipient",
        "flow_id",
        "effect_pp",
        "event_date",
        "days_before_election",
        "retained_fraction",
        "realized_effect_pp",
        "feasible",
        "reason",
        *NAMES,
        "residual",
        "recipient_margin_pp",
        "tie_gain_pp",
        "tie_reachable",
        "max_gain_pp",
    ]
    with (output / "scenarios.csv").open("w", newline="") as file:
        writer = csv.DictWriter(file, fieldnames=fields, lineterminator="\n")
        writer.writeheader()
        for scenario in scenarios:
            timing = timings[scenario["timing_id"]]
            row = {**scenario, **timing, **(scenario["shares"] or {})}
            writer.writerow({key: row.get(key, "") for key in fields})

    lines = [
        "# Tory endorsement scenarios",
        "",
        "Generated by `uv run python scripts/analyze_tory_endorsement.py`.",
        "",
        (
            "[Interactive report](index.html) · [Full grid (CSV)](scenarios.csv) · "
            "[Inputs and results (JSON)](scenarios.json)"
        ),
        "",
        report["interpretation"],
        "",
        (
            "The grid contains 360 scenarios: two independent poll baselines, two recipients, "
            "three vote-flow assumptions, five potential effects (-3/0/+3/+6/+9 points), "
            "two hypothetical event dates, and three assumed retained fractions (0/50/100%). "
            "The settings have no assigned probabilities."
        ),
        "",
        "## Baselines and provenance",
        "",
    ]
    for base in report["baselines"]:
        shares = ", ".join(
            f"{NAMES.get(key, 'Poll residual')} {value:g}%"
            for key, value in base["reported_shares"].items()
        )
        lines += [
            (
                f"- **[{base['label']}]({base['source_url']})**, "
                f"{base['fieldwork_start']}–{base['fieldwork_end']}; "
                f"published {base['publication_date']}; parent n={base['sample_size']}. "
                f"{base['denominator']}: {shares}. "
                f"Reported sum {base['reported_total']:g}%; all values scaled by "
                f"100/{base['reported_total']:g} only for this arithmetic. "
                f"Reading `{base['reading_id']}`; {base['source_locator']}."
            ),
        ]
    lines += [
        "",
        (
            "Source-document and canonical-input SHA-256 hashes are preserved in JSON. "
            "These are fixed dated readings, not a live polling estimate. "
            "The published residual stays fixed and cannot supply or receive transfers."
        ),
        "",
        "## Gain needed to tie the lead",
        "",
        (
            "These thresholds are net realized percentage points against every other named "
            "candidate. A strict lead requires slightly more than the threshold. "
            "They describe arithmetic feasibility, not likelihood. They may lie outside "
            "the illustrative -3 to +9 point grid."
        ),
        "",
        "| Baseline | Recipient | Votes drawn from | Net gain to tie | Available gain | Feasible? |",
        "|---|---|---|---:|---:|---|",
    ]
    for base in report["baselines"]:
        for recipient in ("bradford", "alexander"):
            for flow in report["flows"]:
                result = next(
                    s
                    for s in scenarios
                    if s["baseline_id"] == base["id"]
                    and s["recipient"] == recipient
                    and s["flow_id"] == flow["id"]
                    and s["effect_pp"] == 0
                )
                lines.append(
                    f"| {base['label']} | {NAMES[recipient]} | {flow['label']} | "
                    f"{result['tie_gain_pp']:.2f} | {result['max_gain_pp']:.2f} | "
                    f"{'Yes' if result['tie_reachable'] else 'No'} |"
                )
    lines += [
        "",
        "## Reading the scenarios",
        "",
        (
            "A positive effect transfers support to the endorsed candidate. A negative effect "
            "reverses the specified flows. Net realized effect equals potential effect multiplied "
            "by the selected retained fraction. That fraction includes persistence and any "
            "restriction from already-cast ballots; it is an assumption, not an estimated "
            "exposure or turnout rate. Dates alone never change the result. The 2023 episode "
            "does not identify retention five or 47 days before the election."
        ),
        "",
        (
            "The reference holds dated poll shares and every other campaign change fixed. "
            "It is neither an election-day baseline forecast nor an identified no-endorsement "
            "counterfactual. No causal effect, confidence interval, or win probability is fitted. "
            "Do not add the shifts to post-event polls that may already reflect an endorsement."
        ),
        "",
        (
            "The 2023 first-post-event comparisons were +5 points (Liaison) and +7 (Forum). "
            "Existing momentum and the same-day Star endorsement prevent isolating Tory's "
            "contribution. See [the evidence and modeling memo]"
            "(../john-tory-2023-endorsement-evidence.md) for sources and limits."
        ),
        "",
        (
            "The [pretrend and council comparison analysis]"
            "(../endorsement-identification/README.md) calculates 3.6–4.7 points above "
            "Bailão's preceding two to three weeks of momentum, or 5.2–6.5 points using "
            "four weeks. These are joint late-campaign residuals, not a Tory coefficient. "
            "The council audit does not yet supply a causal Star effect to subtract."
        ),
        "",
        (
            "Verification: every emitted feasible scenario conserves 100 points and has no "
            "negative support; infeasible scenarios expose an explanation instead of a result. "
            "Canonical readings and forecast feeds are read-only. No model refresh was run."
        ),
        "",
    ]
    lines += [
        "## Alexander entry dynamics",
        "",
        (
            "The [entry analysis](../alexander-entry-dynamics.md) compares Forum's two July 29 "
            "ballots and Liaison's polls across the launch. The largest net decline is in "
            "Someone else. Sequential questions and repeated cross-sections do not identify "
            "individual switching probabilities."
        ),
        "",
        (
            "The JSON and interactive report also include 120 separate Alexander-growth "
            "illustrations: two baselines, two entry-derived allocation assumptions, five "
            "potential shifts and six date/retention settings. These allow the Other response "
            "to shrink within a fixed decided/leaning denominator. They do not alter the 360 "
            "named-candidate transfer scenarios above. Reverse-flow cases are unavailable "
            "because entry data does not supply a loss or withdrawal model."
        ),
        "",
        "| Baseline | Assumed entry mix | Maximum additional Alexander gain | Limiting source |",
        "|---|---|---:|---|",
    ]
    for base in report["baselines"]:
        for profile in report["alexander_entry"]["profiles"]:
            row = next(
                item
                for item in report["alexander_entry"]["extensions"]
                if item["baseline_id"] == base["id"] and item["profile_id"] == profile["id"]
            )
            lines.append(
                f"| {base['label']} | {profile['label']} | {row['max_gain_pp']:.2f} pp | "
                f"{NAMES.get(row['limiting_source'], 'Someone else')} |"
            )
    lines.append("")
    lines += [
        "## Challenger consolidation",
        "",
        (
            "The [consolidation analysis](../tory-consolidation-dynamics.md) separates "
            "Bailão's share of a selected candidate pool from growth of that pool. "
            "The source-linked historical transcription and its SHA-256 are included in JSON. "
            "These descriptive ratios do not identify voters' ideology, individual switches "
            "or Tory's causal contribution."
        ),
        "",
        (
            "Another 404 scenarios transfer 0–100% (one-percent steps) of the other "
            "challenger's support to the recipient, for two baselines and two recipients. "
            "This fraction is a chosen net realized transfer, independent of the point-shift "
            "and timing settings. Chow and the residual stay fixed; Bradford plus Alexander "
            "is conserved. A common slider permits comparison, not an assumption that the "
            "two endorsements are equally effective. The CSV remains the original 360-row "
            "point grid; all consolidation inputs and results are in JSON."
        ),
        "",
        "| Baseline | Combined ceiling | Margin against Chow after full consolidation |",
        "|---|---:|---:|",
    ]
    for base in report["baselines"]:
        row = next(
            item
            for item in report["consolidation"]["scenarios"]
            if item["baseline_id"] == base["id"] and item["rival_fraction"] == 1
        )
        lines.append(
            f"| {base['label']} | {row['pool_share_pp']:.2f}% | "
            f"{row['full_consolidation_margin_pp']:+.2f} pp |"
        )
    lines += [
        "",
        (
            "The additional-Chow-transfer requirement is a separate arithmetic threshold "
            "after the chosen consolidation. It checks both named opponents, is not silently "
            "applied, and does not model new turnout or undecided voters. All baselines retain "
            "their original published values alongside the normalized arithmetic shares."
        ),
        "",
    ]
    (output / "README.md").write_text("\n".join(lines))
    print(
        f"Verified {len(scenarios)} endorsement scenarios and "
        f"{len(report['alexander_entry']['extensions'])} growth illustrations; "
        f"{len(report['consolidation']['scenarios'])} consolidation scenarios; "
        f"report: {output / 'index.html'}"
    )


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=ROOT / "docs/research/tory-endorsement-scenarios",
    )
    write_report(parser.parse_args().output_dir)
